name: build
on:
  push:
    branches: [ main ]
jobs:
  build:

    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2


      - name: Build Docker Image
        run: docker build -t az-vue-image .

      - name: Run Docker image
        run: docker run -d -p 8082:80 --name az-vue-container az-vue-image
